name: Build CHORIFY 2 APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build CHORIFY 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant execute permission to Gradle
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
          else
            echo "ERROR: gradlew file not found!"
            exit 1
          fi

      - name: Check Java version
        run: java -version

      - name: Check Gradle version
        run: ./gradlew --version

      - name: Build CHORIFY 2 Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Find generated APK
        run: |
          echo "Searching for APK..."
          find . -type f -name "*.apk" -print

      - name: Upload CHORIFY 2 APK
        uses: actions/upload-artifact@v4
        with:
          name: CHORIFY-2-debug-APK
          path: |
            **/build/outputs/apk/debug/*.apk
          if-no-files-found: error
